#!groovy

// Generated by IBM TransformationAdvisor
// Wed Apr 03 06:03:12 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}